version: '3'

services:
  flask_app:
    image: wappr:flask_gunicorn
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    command: gunicorn -w 3 -b 0.0.0.0:5000 app:app
  
  nginx:
    image: wappr:own_nginx
    container_name: nginx_running
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app